---

- name: deploy | get template 
  vmware.vmware_rest.vcenter_vm_info:
    vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
    vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    filter_names:
    - "{{ vm_template }}"
    vcenter_validate_certs: False
  register: vm_info
  delegate_to: localhost

- name: deploy | get cluster info
  vmware.vmware_rest.vcenter_cluster_info:
    vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
    vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    filter_names:
    #- "{{ vm_cluster }}"
    vcenter_validate_certs: False
  register: cluster_info
  delegate_to: localhost

- name: deploy | get Resource info for {{ vm_cluster }}
  vmware.vmware_rest.vcenter_cluster_info:
    vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
    vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    vcenter_validate_certs: False
    cluster: "{{ cluster_info.value[0].cluster }}"
  register: resource_pool_info
  delegate_to: localhost

- name: deploy | get datastore info
  vmware.vmware_rest.vcenter_datastore_info:
    vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
    vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    vcenter_validate_certs: False
    filter_names:
    #- "{{ vm_datastore }}"
  register: datastore_info
  delegate_to: localhost

- name: deploy | get folder info
  vmware.vmware_rest.vcenter_folder_info:
    vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
    vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    vcenter_validate_certs: False
    filter_names:
    #- '{{ vm_folder }}'
  register: folder_info
  delegate_to: localhost

- set_fact:
    source_vm_id: "{{ vm_info.value[0].vm }}"
    cluster_id: '{{ cluster_info.value[0].cluster }}'
    datastore_id: '{{ datastore_info.value[0].datastore }}'
    folder_id: '{{ folder_info.value[0].folder }}'

- name: deploy | clone from template
  vmware.vmware_rest.vcenter_vm:
    vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
    vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    vcenter_validate_certs: no
    placement:
      cluster: "{{ cluster_id }}"
      datastore: "{{ datastore_id }}"
      folder: "{{ folder_id }}"
    name: "{{ vm_name }}"
    #guest_OS: "RHEL_8_64"
    cpu:
      hot_add_enabled: true
      count: "{{ vm_cpu }}"
    memory:
      hot_add_enabled: true
      size_MiB: "{{ vm_ram }}"
    source: "{{ source_vm_id }}"
    state: clone
    power_on: no
  delegate_to: localhost

- name: Sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20
  delegate_to: localhost

- name: deploy | get template vm "{{ vm_name }}.{{ domain }}"
  vmware.vmware_rest.vcenter_vm_info:
    vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
    vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
    vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
    filter_names:
    - "{{ vm_name }}.{{ domain }}"
    vcenter_validate_certs: False
  register: vm_info_new
  delegate_to: localhost

- name: Customize the VM
  vmware.vmware_rest.vcenter_vm_guest_customization:
    vm: "{{ vm_info_new.value[0].vm }}"
    configuration_spec:
      linux_config:
        domain: "my-lab.local"
        hostname:
          fixed_name: "{{ vm_name }}"
          type: FIXED
    interfaces:
    - adapter:
        ipv4:
          type: STATIC
          gateways:
          - 192.168.1.1
          ip_address: "192.168.1.41"
          prefix: 24
    global_DNS_settings:
      dns_suffix_list: []
      dns_servers:
      - 192.168.1.31

- name: Start the VM
  vmware.vmware_rest.vcenter_vm_power:
    state: start
    vm: "{{ vm_info_new.value[0].vm }}"

- name: Wait until SSH port is UP
  wait_for:
    port: 22
    host: "{{ vm_ip }}"
    search_regex: OpenSSH
    delay: 20
  vars:
    ansible_connection: local
