---

# all
ansible_vmware_validate_certs: no
ansible_connection: vmware_tools
ansible_vmware_guest_path: "DC1/vm/"
ansible_vmware_tools_user: admin
ansible_vmware_tools_password: admin
vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"

# fortianalyzer
vm_name: fortianalyzer-1
vm_template: fortianalyzer
vm_cluster: cluster1
vm_datastore: datastore2
vm_folder: vm
vm_cpu: 4
vm_ram: 8

