---

# Create Execution Environment

- name: Create Execution Environment
  awx.awx.execution_environment:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "(auto) Fortinet Execution Environment"
    image: quay.io/rh_ee_cparada/ee-supported-rh-cparada-fortinet
    pull: always
    credential: "Credentials: quay.io"
    state: present

# Create Project

- name: Create Project
  awx.awx.project:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "(auto) Fortinet Project"
    description: Created by Ansible Automation
    organization: Default
    scm_update_on_launch: True
    scm_type: git
    scm_url: "https://github.com/carlosfparada/Fortinet.git"
    state: present

# Create Credentials

- name: Create Credentials
  awx.awx.credential:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "(auto) Fortinet Credentials"
    description: Created by Ansible Automation
    organization: Default
    credential_type: Machine
    inputs:
      username: "{{ fortinet_username }}"
      password: "{{ fortinet_password }}"
    state: present

# Create Templates

- name: Create Job Template wmware
  awx.awx.job_template:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "(auto) Fortinet Job Template vmware"
    description: Created by Ansible Automation
    organization: Default
    job_type: run
    execution_environment: "(auto) Fortinet Execution Environment"
    inventory: "Inventory: Fortinet"
    project: "(auto) Fortinet Project"
    playbook: vmware.yml
    credentials:
      - "(auto) Fortinet Credentials"
    state: present

- name: Create Job Template fortigate
  awx.awx.job_template:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "(auto) Fortinet Job Template fortigate"
    description: Created by Ansible Automation
    organization: Default
    job_type: run
    execution_environment: "(auto) Fortinet Execution Environment"
    inventory: "Inventory: Fortinet"
    project: "(auto) Fortinet Project"
    playbook: fortigate.yml
    credentials:
      - "(auto) Fortinet Credentials"
    state: present

- name: Create Job Template fortianalyzer
  awx.awx.job_template:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "(auto) Fortinet Job Template fortianalyzer"
    description: Created by Ansible Automation
    organization: Default
    job_type: run
    execution_environment: "(auto) Fortinet Execution Environment"
    inventory: "Inventory: Fortinet"
    project: "(auto) Fortinet Project"
    playbook: fortianalyzer.yml
    credentials:
      - "(auto) Fortinet Credentials"
    state: present

- name: Create Job Template fortianalyzer-wa
  awx.awx.job_template:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "(auto) Fortinet Job Template fortianalyzer-wa"
    description: Created by Ansible Automation
    organization: Default
    job_type: run
    execution_environment: "(auto) Fortinet Execution Environment"
    inventory: "Inventory: Fortinet"
    project: "(auto) Fortinet Project"
    playbook: fortianalyzer-wa.yml
    credentials:
      - "(auto) Fortinet Credentials"
    state: present

- name: Create Job Template fortimanager
  awx.awx.job_template:
    validate_certs: no
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "(auto) Fortinet Job Template fortimanager"
    description: Created by Ansible Automation
    organization: Default
    job_type: run
    execution_environment: "(auto) Fortinet Execution Environment"
    inventory: "Inventory: Fortinet"
    project: "(auto) Fortinet Project"
    playbook: fortimanager.yml
    credentials:
      - "(auto) Fortinet Credentials"
    state: present
