---

domain: "root"
fortigate_name: "FortiGate-VM64"

ansible_network_os: fortinet.fortianalyzer.fortianalyzer
ansible_connection: httpapi
ansible_httpapi_use_ssl: no
ansible_httpapi_validate_certs: no
ansible_httpapi_port: 80
